"""Initial migration

Revision ID: fbed62049804
Revises: 
Create Date: 2025-02-25 21:01:31.611730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbed62049804'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute('CREATE TEMPORARY TABLE temp_categories ON COMMIT DROP AS SELECT * FROM categories')
    # op.execute('CREATE TEMPORARY TABLE temp_products ON COMMIT DROP AS SELECT * FROM products')
    # op.execute('CREATE TEMPORARY TABLE temp_users ON COMMIT DROP AS SELECT * FROM users')
    # op.execute('CREATE TEMPORARY TABLE temp_ratings ON COMMIT DROP AS SELECT * FROM ratings')
    # op.execute('CREATE TEMPORARY TABLE temp_reviews ON COMMIT DROP AS SELECT * FROM reviews')
    # op.drop_table('reviews')
    # op.drop_table('ratings')
    # op.drop_index('ix_ecommerce_fastapi_products_slug', table_name='products')
    # op.drop_table('products')
    # op.drop_index('ix_ecommerce_fastapi_users_email', table_name='users')
    # op.drop_index('ix_ecommerce_fastapi_users_username', table_name='users')
    # op.drop_table('users')
    # op.drop_index('ix_ecommerce_fastapi_categories_slug', table_name='categories')
    # op.drop_table('categories')
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['ecommerce_fastapi.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce_fastapi'
    )
    op.create_index(op.f('ix_ecommerce_fastapi_categories_slug'), 'categories', ['slug'], unique=True, schema='ecommerce_fastapi')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_supplier', sa.Boolean(), nullable=False),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce_fastapi'
    )
    op.create_index(op.f('ix_ecommerce_fastapi_users_email'), 'users', ['email'], unique=True, schema='ecommerce_fastapi')
    op.create_index(op.f('ix_ecommerce_fastapi_users_username'), 'users', ['username'], unique=True, schema='ecommerce_fastapi')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ecommerce_fastapi.categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['ecommerce_fastapi.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='ecommerce_fastapi'
    )
    op.create_index(op.f('ix_ecommerce_fastapi_products_slug'), 'products', ['slug'], unique=True, schema='ecommerce_fastapi')
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce_fastapi.products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['ecommerce_fastapi.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id'),
    schema='ecommerce_fastapi'
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('comment_date', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['ecommerce_fastapi.products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rating_id'], ['ecommerce_fastapi.ratings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ecommerce_fastapi.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating_id'),
    schema='ecommerce_fastapi'
    )
    # op.execute('INSERT INTO categories SELECT * FROM temp_categories')
    # op.execute('INSERT INTO users SELECT * FROM temp_users')
    # op.execute('INSERT INTO products SELECT * FROM temp_products')
    # op.execute('INSERT INTO reviews SELECT * FROM temp_reviews')
    # op.execute('INSERT INTO ratings SELECT * FROM temp_ratings')
    # op.execute('''
    # do language plpgsql
    # $$
        # declare
            # max_val int;
            # seq_name text;
        # begin
            # select
                # max(id) into max_val
            # from
                # ecommerce_fastapi.categories;

            # select
                # relname into seq_name
            # from
                # pg_depend d
            # join
                # pg_class c
                # on d.objid = c.oid
            # where
                # refobjid = 'ecommerce_fastapi.categories'::regclass::oid
                # and relkind = 'S'
                # and relnamespace = 'ecommerce_fastapi'::regnamespace::oid;

            # execute format('ALTER SEQUENCE ecommerce_fastapi.%s RESTART WITH %s', seq_name, max_val + 1);
        # end;
    # $$'''
    # )
    # op.execute('''
    # do language plpgsql
    # $$
        # declare
            # max_val int;
            # seq_name text;
        # begin
            # select
                # max(id) into max_val
            # from
                # ecommerce_fastapi.products;

            # select
                # relname into seq_name
            # from
                # pg_depend d
            # join
                # pg_class c
                # on d.objid = c.oid
            # where
                # refobjid = 'ecommerce_fastapi.products'::regclass::oid
                # and relkind = 'S'
                # and relnamespace = 'ecommerce_fastapi'::regnamespace::oid;

            # execute format('ALTER SEQUENCE ecommerce_fastapi.%s RESTART WITH %s', seq_name, max_val + 1);
        # end;
    # $$'''
    # )
    # op.execute('''
    # do language plpgsql
    # $$
        # declare
            # max_val int;
            # seq_name text;
        # begin
            # select
                # max(id) into max_val
            # from
                # ecommerce_fastapi.users;

            # select
                # relname into seq_name
            # from
                # pg_depend d
            # join
                # pg_class c
                # on d.objid = c.oid
            # where
                # refobjid = 'ecommerce_fastapi.users'::regclass::oid
                # and relkind = 'S'
                # and relnamespace = 'ecommerce_fastapi'::regnamespace::oid;

            # execute format('ALTER SEQUENCE ecommerce_fastapi.%s RESTART WITH %s', seq_name, max_val + 1);
        # end;
    # $$'''
    # )
    # op.execute('''
    # do language plpgsql
    # $$
        # declare
            # max_val int;
            # seq_name text;
        # begin
            # select
                # max(id) into max_val
            # from
                # ecommerce_fastapi.users;
                
            # select
                # relname into seq_name
            # from
                # pg_depend d
            # join
                # pg_class c
                # on d.objid = c.oid
            # where
                # refobjid = 'ecommerce_fastapi.reviews'::regclass::oid
                # and relkind = 'S'
                # and relnamespace = 'ecommerce_fastapi'::regnamespace::oid;

            # execute format('ALTER SEQUENCE ecommerce_fastapi.%s RESTART WITH %s', seq_name, 1);
        # end;
    # $$'''
    # )
    # op.execute('''
    # do language plpgsql
    # $$
        # declare
            # max_val int;
            # seq_name text;
        # begin
            # select
                # max(id) into max_val
            # from
                # ecommerce_fastapi.users;
                
            # select
                # relname into seq_name
            # from
                # pg_depend d
            # join
                # pg_class c
                # on d.objid = c.oid
            # where
                # refobjid = 'ecommerce_fastapi.ratings'::regclass::oid
                # and relkind = 'S'
                # and relnamespace = 'ecommerce_fastapi'::regnamespace::oid;

            # execute format('ALTER SEQUENCE ecommerce_fastapi.%s RESTART WITH %s', seq_name, 1);
        # end;
    # $$'''
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='categories_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_ecommerce_fastapi_categories_slug', 'categories', ['slug'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('comment_date', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='reviews_product_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], name='reviews_rating_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey'),
    sa.UniqueConstraint('rating_id', name='reviews_rating_id_key')
    )
    op.create_table('ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='ratings_product_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ratings_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='ratings_pkey'),
    sa.UniqueConstraint('user_id', 'product_id', name='ratings_user_id_product_id_key')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='products_category_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], name='products_supplier_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.create_index('ix_ecommerce_fastapi_products_slug', 'products', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_supplier', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_customer', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_ecommerce_fastapi_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_ecommerce_fastapi_users_email', 'users', ['email'], unique=True)
    op.drop_table('reviews', schema='ecommerce_fastapi')
    op.drop_table('ratings', schema='ecommerce_fastapi')
    op.drop_index(op.f('ix_ecommerce_fastapi_products_slug'), table_name='products', schema='ecommerce_fastapi')
    op.drop_table('products', schema='ecommerce_fastapi')
    op.drop_index(op.f('ix_ecommerce_fastapi_users_username'), table_name='users', schema='ecommerce_fastapi')
    op.drop_index(op.f('ix_ecommerce_fastapi_users_email'), table_name='users', schema='ecommerce_fastapi')
    op.drop_table('users', schema='ecommerce_fastapi')
    op.drop_index(op.f('ix_ecommerce_fastapi_categories_slug'), table_name='categories', schema='ecommerce_fastapi')
    op.drop_table('categories', schema='ecommerce_fastapi')
    # ### end Alembic commands ###
