name: fastapi-ecommerce-prod
services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    # command: gunicorn app.main:app --workers 4 --worker-class uvicorn_worker.UvicornWorker --bind 0.0.0.0:8000
    command: uvicorn app.main:app --workers 4 --host 0.0.0.0 --port 8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=homedb1007
      - POSTGRES_DB=homedb

  nginx:
    build: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      
  # certbot:
    # image: certbot/certbot
    # volumes:
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    # command: certonly --webroot --webroot-path=/var/www/certbot/ --email --agree-tos --no-eff-email -d
    # depends_on:
      # - nginx

volumes:
  postgres_data: